### ISSUE TITLE
Discuss and generate Team workflow practices

### ISSUE THREAD

**Issue by HimanshuRanka** [serotracker/Serotracker#10]
As a new team, we have the freedom of figuring out how we work best individually and together and what sets of tools we need to deliver work efficiently and successfully. 

We will discuss much about these working strategies, make a note of working styles we like, update our issue tracker in a way that gives us the information we need and then get started on the process. 

Things to consider
- Workflows
- Synchronous working time
- Ticket making and resolution
- Feature enhancements
- Bug tracking
- External team review

**Comment by SeanKennyNF** [comment]
Hey friends :heart:

I opened an issue and a pretty uncontroversial (hopefully lol) PR real quick just to get kicked off, all comfortable with each other, and have some kind of process to iterate on even if it's a bit silly :)

I requested everyone, if you're opening PRs and stuff, please feel free to request me, I like to feel in the loop and talk with other people so please don't be shy! I generally try to at least take a quick skim of everything I'm requested on even if I don't leave a review and I'd like to think I'm okay at getting back to people quickly hahaha

Anyways here's the PR https://github.com/PathoTracker/Pathotracker/pull/12, I assume that merging the PR will kick off the vercel production pipeline so I'll probably hit it after I get a couple approvals if that's alright. The preview looks good to me so I think we're :100:
