### ISSUE TITLE
Create all Arbo Visualizations

### ISSUE THREAD

**Issue by HimanshuRanka** [serotracker/Serotracker#24]
There are several visualizations for the arbotracker side of things that we already have. These can be found here: https://docs.google.com/document/d/1YsIj7Cv2cA2XY_QM4TKHeDFWsY3rBI-V/edit

Each of these visualizations need to implemented to match the styling that currently exists and displayed on the analyze page. 

The relevant R code that was used to generate these visualizations can be found here: https://github.com/serotracker/arbo_viz/blob/main/script/arbo_viz.qmd

Update the visualizations on the dashboard page to be smaller, selectable and collapsible. 

Update the Viz titles, axis titles and legends to be more descriptive

**Comment by harrietware** [comment]
Figures to include in the alpha are highlighted yellow

**Comment by HimanshuRanka** [comment]
Taking a look at the recharts library and it is so much more intuitive so I am going to attempt to create the new visualizations using that library and if it looks nicer and feels better I will change the nivo vis ones to recharts too
